# Generated by Django 3.2.4 on 2021-06-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.FileField(default='image.jpg', upload_to='images'),
        ),
    ]
